### PR TITLE
mainly build system fixes

### PR DESCRIPTION
**Pull request by K-os**
- cleanup cmake toolchain files
- add ubuntu armv7 toolchain file (gh: #175)
- fix build with TARGET_SIMD_X86 disabled (gh: #175)
- impove target architecture detection heuristics
- don't build avx2 files, when not needed
- fix windows for arm64 builds (untested)

### CODE REVIEW

**Comment by shijunz** [comment]
> * fix windows for arm64 builds (untested)
I am trying to build the windows-arm64 version now. I want to know how to configure the cmake cmd for the windows arm64? could you help me? I do not think it is easy way to do ,

I think the most of work should be about the simde modules? or someone use the simde module for windows arm64 before?

thanks in advances.

**Comment by K-os** [comment]
It does compile with SIMD-Everywhere enabled (the default) for ARM64 using Visual Studio, but since we don't have an ARM based windows machine, it's untested.

Feel free to give it a try and report your findings.

**Comment by shijunz** [comment]
> It does compile with SIMD-Everywhere enabled (the default) for ARM64 using Visual Studio, but since we don't have an ARM based windows machine, it's untested.
> 
> Feel free to give it a try and report your findings.

yes, I have two ARM based windows  machine, could you share me the detail? how to build windows arm64? I am happy to test it.

**Comment by K-os** [comment]
Using the top-level Makefile add the parameter `msvc-arch=arm64` to your make call, or if you are using CMake directly add the parameter `-A arm64` to your cmake commandline.

A good first test would be to run the test-suite for example:
```
make msvc-arch=arm64  enable-bitstream-download=1 release
make test
```
or like this:
```
cmake -A arm64 -B build/win_arm64 -DVVDEC_ENABLE_BITSTREAM_DOWNLOAD=ON
cmake --build build/win_arm64
cmake --build build/win_arm64 -t test
```

**Pull request merged**
